name: feature_wallet
description: "A new Flutter package project."
version: 0.0.1
homepage:

publish_to: none

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.1.4
  fluttertoast: ^9.0.0
  json_annotation: ^4.8.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  flutter_riverpod: ^2.5.1
  flutter_screenutil: ^5.8.4
  easy_refresh: ^3.3.2+1
  solana_wallet: ^0.0.4
  get: ^4.6.6
  decimal: ^2.3.3
  image_picker: ^1.2.0
  shimmer: ^3.0.0
  bip39: ^1.0.6
  bip32: ^2.0.0
  hex: ^0.2.0
  http: ^1.4.0
  solana: ^0.31.0+1
  flutter_secure_storage: ^8.0.0
  walletconnect_dart: ^0.0.11
  web3dart: ^2.7.1
  webview_flutter: ^4.4.0
  cryptography: ^2.7.0
  ed25519_hd_key: ^2.3.0
  bs58: ^1.0.2
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.1.2
  slang: ^4.11.0
  slang_flutter: ^4.11.0
  shared_ui:
    path: ../shared_ui
  shared_utils:
    path: ../shared_utils
  shared_setting:
    path: ../shared_setting

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.0
  json_serializable: ^6.7.1
  slang_build_runner: ^4.11.0
  freezed: ^2.5.2  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
