name: untitled1
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
    
  decimal: ^2.3.3
  flutter_inappwebview: ^6.1.5
  slang: ^4.8.1
  slang_flutter: ^4.8.0
  bs58: ^1.0.2
  image_picker: ^1.2.0
  photo_manager: ^3.5.1
  mobile_scanner: ^7.1.2
  qr_flutter: ^4.1.0
  solana_web3: ^0.1.3
  solana_wallet: ^0.0.4
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.3.2
  package_info_plus: ^8.0.0
  ota_update: ^7.0.2
  pub_semver: ^2.2.0
  badges: ^3.1.2
  #屏幕适配
  flutter_screenutil: ^5.8.4
  #响应式状态管理
  get: ^4.6.6
  provider: ^6.0.5
  #路由跳转
  fluro: ^2.0.3
  #网络请求
  dio: ^5.3.3
  http: ^1.4.0
  #下拉刷新
  easy_refresh: ^3.3.2+1
  #弹窗提示
  fluttertoast: ^9.0.0
  #本地数据存储
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # 用于生成适配器
  hive_generator: ^2.0.0
  build_runner: ^2.4.0
  #序列化
  json_annotation: ^4.8.1
  #权限申请
#  permission_handler: ^11.0.1
  #消息滚动
  marquee: ^2.2.1
  #拼音转换
  lpinyin: ^2.0.0
  #虚拟钱包
#  trust_wallet_core: ^0.0.6
#  flutter_trust_wallet_core: ^0.0.1
#  wallet_core_bindings: ^4.3.6
  web3dart: ^2.7.1
  # 多链支持
  walletconnect_dart: ^0.0.11
  # 助记词生成
  bip39: ^1.0.6
  # 需要FFI支持
  ffi: ^2.0.1
  # 文件路径处理（可选）
  path_provider: ^2.1.1
  # 安全存储
  flutter_secure_storage: ^8.0.0
  #加密工具
  crypto: ^3.0.3
  hex: ^0.2.0
  ed25519_hd_key: ^2.3.0
  #solana支持
  solana: ^0.31.0+1
  #比特币支持
  bip32: ^2.0.0
  bs58check: ^1.0.2
  # DApp浏览器支持
  url_launcher: ^6.1.11
  # DApp浏览器
  webview_flutter: ^4.4.0
  #桌面图标生成
  flutter_launcher_icons: ^0.13.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  cryptography: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  build_runner: ^2.4.0
  json_serializable: ^6.7.1
  slang_build_runner: ^4.8.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/icon/TT_icon.jpg
    - assets/icon/app_icon_launch.png
    - assets/images/ic_arrows_right.png
    - assets/images/ic_arrows_down.png
    - assets/images/ic_tab_home.png
    - assets/images/ic_tab_discovery.png
    - assets/images/ic_tab_situation.png
    - assets/images/ic_tab_trade.png
    - assets/images/ic_tab_wallet.png
    - assets/images/ic_home_function.png
    - assets/images/ic_home_link.png
    - assets/images/ic_home_scan.png
    - assets/images/ic_home_search.png
    - assets/images/ic_home_message.png
    - assets/images/ic_clip_photo.png
    - assets/images/ic_home_grid_collection.png
    - assets/images/ic_home_grid_contract.png
    - assets/images/ic_home_grid_more.png
    - assets/images/ic_home_grid_profitable.png
    - assets/images/ic_home_grid_radar.png
    - assets/images/ic_home_app_icon.png
    - assets/images/ic_home_app_icon1.png
    - assets/images/ic_home_app_icon2.png
    - assets/images/ic_home_app_icon3.png
    - assets/images/ic_home_visa.png
    - assets/images/ic_home_master.png
    - assets/images/ic_home_applepay.png
    - assets/images/bg_home_banner.png
    - assets/images/ic_home_sound.png
    - assets/images/ic_home_sort_default.png
    - assets/images/ic_home_bit_coin.png
    - assets/images/ic_wallet_grid.png
    - assets/images/ic_wallet_new_work_selected.png
    - assets/images/ic_wallet_reminder.png
    - assets/images/ic_wallet_selected.png
    - assets/images/ic_wallet_exclamation.png
    - assets/images/ic_wallet_query.png
    - assets/images/ic_wallet_create.png
    - assets/images/ic_wallet_import.png
    - assets/images/ic_wallet_hardware.png
    - assets/images/ic_wallet_observe.png
    - assets/images/ic_wallet_create_helper.png
    - assets/images/ic_wallet_create_private_key.png
    - assets/images/ic_wallet_backup1.png
    - assets/images/ic_wallet_backup2.png
    - assets/images/ic_wallet_backup3.png
    - assets/images/ic_wallet_unselected.png
    - assets/images/ic_wallet_un_eye.png
    - assets/images/ic_wallet_edit.png
    - assets/images/ic_wallet_drag_handle.png
    - assets/images/ic_wallet_copy.png
    - assets/images/ic_wallet_safety_error.png
    - assets/images/ic_wallet_transfer.png
    - assets/images/ic_wallet_finance.png
    - assets/images/ic_wallet_gat_gas.png
    - assets/images/ic_wallet_transfer_record.png
    - assets/images/ic_wallet_import_scan.png
    - assets/images/grouping_3.png
    - assets/images/scan_white.png
    - assets/images/read.png
    - assets/images/bell.png
    - assets/images/discord.png
    - assets/images/facebook.png
    - assets/images/Telgram.png
    - assets/images/Twitter_1.png
    - assets/images/moon.png
    - assets/images/hint.png
    - assets/images/bind_count_image.png
    - assets/images/BNB.png
    - assets/images/BTC.png
    - assets/images/ETH.png
    - assets/images/USDT.png
    - assets/images/rewardsAccount_popup_img.png
    - assets/images/authorization_detection.png
    - assets/images/bank_card.png
    - assets/images/batch_transfers.png
    - assets/images/beginner's_guide.png
    - assets/images/blockchain_explorer.png
    - assets/images/buy_coins.png
    - assets/images/c2c.png
    - assets/images/contract.png
    - assets/images/contract_testing.png
    - assets/images/earn_coins.png
    - assets/images/EIP-7702_detection.png
    - assets/images/financial_management.png
    - assets/images/get_gas.png
    - assets/images/golden_dog_radar.png
    - assets/images/invitation_center.png
    - assets/images/limit_order.png
    - assets/images/meme_pump.png
    - assets/images/receiving_payments.png
    - assets/images/red_envelope.png
    - assets/images/rewards_account.png
    - assets/images/shopping.png
    - assets/images/SOL_rental_recovery.png
    - assets/images/transaction_history.png
    - assets/images/transfer.png
    - assets/images/all_network.png
    - assets/images/solana_logo.png
    - assets/images/addressBook.png
    - assets/images/fiery_first.png
    - assets/images/fiery_second.png
    - assets/images/fiery_third.png
    - assets/images/no_transaction.png

    - assets/images/bg_jiaoyi.jpg
    - assets/images/bg_jiaoyiheyue.jpg
    - assets/images/bg_jingouleida.jpg
    - assets/images/bg_marking_coin.jpg
    - assets/images/bg_hotlist.jpg
    - assets/images/bg_hangqingjihui.jpg
    - assets/images/bg_hangqingqushi.jpg
    - assets/images/ic_home_center_imge.jpg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/TT_icon.jpg"  # 1024x1024像素的图标
  # 可选自适应图标配置（Android 8.0+）
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icon/TT_icon.jpg"
  min_sdk_android: 21
  #修改后运行命令:
  #flutter clean
  #flutter pub run flutter_launcher_icons:main -f pubspec.yaml

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
dependency_overrides:
  pinenacl: ^0.6.0
