name: shared_utils
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  shared_preferences: ^2.3.2
  dio: ^5.3.3
  crypto: ^3.0.3
  hive: ^2.2.3
  path_provider: ^2.1.4
  hive_flutter: ^1.1.0
  http: ^1.4.0
  bip39: ^1.0.6
  solana: ^0.31.0+1
  pub_semver: ^2.2.0
  ota_update: ^7.0.2
  url_launcher: ^6.1.11
  package_info_plus: ^8.0.0
  decimal: ^2.3.3
  local_auth: ^2.3.0
  flutter_svg: ^2.0.10+1
  flutter_local_notifications: ^19.5.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
