name: feature_main
description: "A new Flutter package project."
version: 0.0.1
homepage:

publish_to: none

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  carousel_slider: ^5.1.1
  fluttertoast: ^9.0.0
  slang: ^4.11.0
  slang_flutter: ^4.11.0
  get: ^4.6.6
  flutter_screenutil: ^5.8.4
  easy_refresh: ^3.3.2+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_riverpod: ^2.5.1
  badges: ^3.1.2
  shared_preferences: ^2.3.2
  hex: ^0.2.0
  ed25519_hd_key: ^2.3.0
  solana_web3: ^0.1.3
  package_info_plus: ^8.0.0
  pub_semver: ^2.2.0
  feature_wallet:
    path: ../feature_wallet
  shared_setting:
    path: ../shared_setting
  feature_browser:
    path: ../feature_browser
  shared_ui:
    path: ../shared_ui
  feature_im:
    path: ../feature_im

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.0
  json_serializable: ^6.7.1
  slang_build_runner: ^4.11.0
  freezed: ^2.5.2  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
dependency_overrides:
  pinenacl: ^0.6.0